name: Go

on:
  create:
    tags:
      - v*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        sed -i "s/var IsDevelopment = true/var IsDevelopment = false/g" Logger/Logger.go
        #for GOOSV in darwin linux; do
          #for GOARCHV in 386 amd64; do
        for GOOSV in linux; do
          for GOARCHV in amd64; do
            #env GOOS=$GOOSV GOARCH=$GOARCHV CGO_ENABLED=0 go build -v -a -ldflags '-s -w' -o ./bin/ogame-bot-$GOOSV-$GOARCHV
            env GOOS=$GOOSV GOARCH=$GOARCHV CGO_ENABLED=0 go build -v -a -ldflags '-s -w' -o ./bin/ogame-bot-$GOOSV-$GOARCHV
          done
        done
        for GOOSV in windows; do
          for GOARCHV in 386 amd64; do
            #env GOOS=$GOOSV GOARCH=$GOARCHV CGO_ENABLED=0 go build -v -a -ldflags '-s -w' -o ./bin/ogame-bot-$GOOSV-$GOARCHV.exe
            env GOOS=$GOOSV GOARCH=$GOARCHV CGO_ENABLED=0 go build -v -a -ldflags '-s -w' -o ./bin/ogame-bot-$GOOSV-$GOARCHV.exe
          done
        done
        
